name: Deploy Docker App to Azure Web App

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: 'appservice' # 본인의 앱 이름 확인!
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # 1. 깃허브 컨테이너 저장소 로그인
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 2. 도커 이미지 빌드 및 업로드
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    # 🛑 이곳에 있던 Azure Login 스텝은 영원히 삭제되었습니다. 🛑

    # 3. 마스터키를 이용한 다이렉트 배포
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest'